/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Entities.RecipeIngredient;

public class Ingredient extends javax.swing.JPanel {

    /**
     * Creates new form Ingredient
     */
    private final RecipeIngredient ingredient;
    
    public Ingredient(RecipeIngredient ingredient) {
        initComponents();
        this.ingredient = ingredient;
        jLabel1.setText(ingredient.getName());
    }
    
    public RecipeIngredient getIngredient() {
        return this.ingredient;
    }
    
    public boolean isSelected() {
        return jCheckBox1.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(170, 40));
        setMinimumSize(new java.awt.Dimension(170, 40));
        setPreferredSize(new java.awt.Dimension(170, 40));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Name");
        jLabel1.setFocusable(false);
        add(jLabel1, java.awt.BorderLayout.CENTER);

        jCheckBox1.setText("ADD");
        jCheckBox1.setFocusable(false);
        add(jCheckBox1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
