/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Entities.User;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URLEncoder;
import java.net.http.HttpRequest;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.FontUIResource;
import okhttp3.FormBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     *
     * @throws java.net.URISyntaxException
     */
    private final OkHttpClient httpClient = new OkHttpClient();

    public Login() throws URISyntaxException {
        initComponents();
        setSize(510, 400);
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/login48.png")));
    }

    public static HttpRequest.BodyPublisher ofFormData(Map<Object, Object> data) {
        var builder = new StringBuilder();
        for (Map.Entry<Object, Object> entry : data.entrySet()) {
            if (builder.length() > 0) {
                builder.append("&");
            }
            builder.append(URLEncoder.encode(entry.getKey().toString(), StandardCharsets.UTF_8));
            builder.append("=");
            builder.append(URLEncoder.encode(entry.getValue().toString(), StandardCharsets.UTF_8));
        }
        return HttpRequest.BodyPublishers.ofString(builder.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        usernamePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        passwordPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gmail24.png"))); // NOI18N
        jLabel1.setText("edwinvillacis@yahoo.com");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 360, 240, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Developed By Edwin ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 320, 290, 30);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Recipes Manager");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 0, 390, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close32.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 0, 40, 40);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 180, 72, 30);

        jPanel3.setOpaque(false);

        usernamePanel.setOpaque(false);
        usernamePanel.setPreferredSize(new java.awt.Dimension(240, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/username24.png"))); // NOI18N
        usernamePanel.add(jLabel3);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("edwin.villacis.fsus@gmail.com");
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 30));
        usernamePanel.add(jTextField1);

        jPanel3.add(usernamePanel);

        passwordPanel.setOpaque(false);
        passwordPanel.setPreferredSize(new java.awt.Dimension(240, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password24.png"))); // NOI18N
        passwordPanel.add(jLabel4);

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setText("123");
        jPasswordField1.setPreferredSize(new java.awt.Dimension(200, 30));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        passwordPanel.add(jPasswordField1);

        jPanel3.add(passwordPanel);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(130, 80, 240, 90);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/whatsapp24.png"))); // NOI18N
        jLabel7.setText("+593 96 876 6840");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 360, 170, 30);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 0));
        jButton3.setText("Sign Up");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(420, 300, 77, 24);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loginBackground1.jpg"))); // NOI18N
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 510, 400);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Mall Of Kalowal");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 460, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        authenticateUser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void authenticateUser() {
        if (jTextField1.getText().length() > 0) {
            if (jPasswordField1.getText().length() > 0) {
                RequestBody formBody = new FormBody.Builder()
                        .add("username", jTextField1.getText())
                        .add("password", jPasswordField1.getText())
                        .build();
                Request request = new Request.Builder()
                        .url("http://localhost:8181/api/v1/users/authenticate")
                        .addHeader("User-Agent", "OkHttp Bot")
                        .post(formBody)
                        .build();
                try ( Response response = httpClient.newCall(request).execute()) {
                    if (!response.isSuccessful()) {
                        throw new IOException("Unexpected code " + response);
                    }
                    // Get response body
                    Utils.LoggedUser = new User(response.body().string());
                    if (Utils.LoggedUser != null) {
                        new Home(this).show();
                        jTextField1.setText("");
                        jPasswordField1.setText("");
                        jTextField1.grabFocus();
                        hide();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "User Not Found");
                    }
                } catch (HeadlessException | IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                    System.out.println(ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Enter Password");
                jPasswordField1.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Enter Username");
            jTextField1.grabFocus();
        }
    }

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
//        authentication();
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new SignUp(this, true).show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            authenticateUser();
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//    Metal
//    Nimbus
//    CDE/Motif
//    Windows
//    Windows Classic
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.getLookAndFeelDefaults().put("Button.font", new FontUIResource(new Font("Segoe UI", Font.BOLD, 14)));
                    javax.swing.UIManager.getLookAndFeelDefaults().put("Label.font", new FontUIResource(new Font("Segoe UI", Font.BOLD, 14)));
                    javax.swing.UIManager.getLookAndFeelDefaults().put("CheckBox.font", new FontUIResource(new Font("Segoe UI", Font.PLAIN, 12)));
                    javax.swing.UIManager.getLookAndFeelDefaults().put("TextField.font", new FontUIResource(new Font("Segoe UI", Font.PLAIN, 12)));
                    javax.swing.UIManager.getLookAndFeelDefaults().put("FormattedTextField.font", new FontUIResource(new Font("Segoe UI", Font.PLAIN, 12)));
//                    javax.swing.UIManager.getLookAndFeelDefaults().put("Panel.background", Utils.JPANEL_BACKGROUND_COLOR);
//                    javax.swing.UIManager.getLookAndFeelDefaults().put("ScrollPane.background", Utils.JFRAME_BACKGROUND_COLOR);
//                    javax.swing.UIManager.getLookAndFeelDefaults().put("CheckBox.background", Utils.JPANEL_BACKGROUND_COLOR);
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Login().setVisible(true);

            } catch (URISyntaxException ex) {
                Logger.getLogger(Login.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
